module.exports = {
  apps: [
    {
      name: 'towertamer-frontend',
      cwd: './',
      script: 'yarn',
      args: 'dev:frontend',
      interpreter: 'none',
      env: {
        NODE_ENV: 'development',
      },
      watch: false,
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: './logs/frontend-error.log',
      out_file: './logs/frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'towertamer-backend',
      cwd: './',
      script: 'yarn',
      args: 'dev:backend',
      interpreter: 'none',
      env: {
        NODE_ENV: 'development',
        PORT: 4025,
      },
      watch: false,
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      error_file: './logs/backend-error.log',
      out_file: './logs/backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
};
